import type { AeroLabSourceDefinition } from "@shared/dataEngine";

export const sourceRegistry: AeroLabSourceDefinition[] = [
  {
    id: "worldmonitor",
    name: "World Monitor",
    priority: "A",
    domains: ["aviation", "maritime", "logistics"],
    coverage: "Global",
    accessMethod: "REST_API",
    updateFrequency: "REALTIME",
    status: "prepared",
    license: {
      licenseStatus: "AGPL-3.0-only for source code; API/service boundary required",
      commercialUse: "conditional",
      redistributionAllowed: "conditional",
      attributionRequired: true,
      notes: "Use only documented REST/MCP contracts. Do not copy application source code. API key required for authenticated data calls.",
    },
  },
  {
    id: "ourairports",
    name: "OurAirports",
    priority: "A",
    domains: ["aviation"],
    coverage: "Global",
    accessMethod: "CSV_DOWNLOAD",
    updateFrequency: "WEEKLY",
    status: "active",
    license: {
      licenseStatus: "Public Domain (OurAirports official statement); GitHub mirror under the Unlicense",
      commercialUse: "yes",
      redistributionAllowed: "yes",
      attributionRequired: false,
      notes: "Verified via web search on 2026-09-13 (official page https://ourairports.com/data/ and mirror https://davidmegginson.github.io/ourairports-data/). Active since 2026-09-15: real ingestion pipeline validated end-to-end, 86,080 airports fetched, validated, normalized, and persisted to MySQL (table `airports`) without duplication on re-run.",
    },
  },
  {
    id: "openstreetmap",
    name: "OpenStreetMap",
    priority: "A",
    domains: ["aviation", "maritime", "rail", "road", "logistics"],
    coverage: "Global",
    accessMethod: "BULK_EXTRACT",
    updateFrequency: "MONTHLY",
    status: "prepared",
    license: {
      licenseStatus: "ODbL 1.0",
      commercialUse: "conditional",
      redistributionAllowed: "conditional",
      attributionRequired: true,
      notes: "Use extracts or controlled ingestion for production; do not couple the frontend directly to public OSM APIs.",
    },
  },
  {
    id: "afts",
    name: "African Transport Systems Database",
    priority: "A",
    domains: ["aviation", "maritime", "rail", "road", "logistics"],
    coverage: "Africa",
    accessMethod: "DATASET_FILE_REVIEW_REQUIRED",
    updateFrequency: "ANNUAL",
    status: "prepared",
    license: {
      licenseStatus: "FLAG_FOR_REVIEW",
      commercialUse: "unknown",
      redistributionAllowed: "unknown",
      attributionRequired: true,
      notes: "Candidate regional infrastructure source; activate only after terms are confirmed.",
    },
  },
  {
    id: "portwatch",
    name: "IMF PortWatch",
    priority: "A",
    domains: ["maritime", "logistics"],
    coverage: "Global (port-level)",
    accessMethod: "REST_API_REVIEW_REQUIRED",
    updateFrequency: "DAILY",
    status: "prepared",
    license: {
      licenseStatus: "Review required",
      commercialUse: "unknown",
      redistributionAllowed: "unknown",
      attributionRequired: true,
      notes: "Candidate source for port activity and trade-transport indicators.",
    },
  },
  {
    id: "unctadstat",
    name: "UNCTADstat",
    priority: "A",
    domains: ["maritime", "logistics"],
    coverage: "Global (maritime trade)",
    accessMethod: "DATASET_FILE_REVIEW_REQUIRED",
    updateFrequency: "ANNUAL",
    status: "prepared",
    license: {
      licenseStatus: "Review required",
      commercialUse: "unknown",
      redistributionAllowed: "unknown",
      attributionRequired: true,
      notes: "Candidate source for LSCI, PLSCI, port calls, container traffic, and maritime trade indicators.",
    },
  },
  {
    id: "worldbank",
    name: "World Bank Data",
    priority: "A",
    domains: ["logistics", "road", "rail"],
    coverage: "Global",
    accessMethod: "REST_API",
    updateFrequency: "ANNUAL",
    status: "prepared",
    license: {
      licenseStatus: "Review required per dataset",
      commercialUse: "conditional",
      redistributionAllowed: "conditional",
      attributionRequired: true,
      notes: "Structural indicators only; not real-time mobility data.",
    },
  },
  {
    id: "opensky",
    name: "OpenSky Network",
    priority: "B",
    domains: ["aviation"],
    coverage: "Global (ADS-B coverage dependent)",
    accessMethod: "REST_API_REVIEW_REQUIRED",
    updateFrequency: "REALTIME",
    status: "prepared",
    license: {
      licenseStatus: "Review required",
      commercialUse: "unknown",
      redistributionAllowed: "unknown",
      attributionRequired: true,
      notes: "Candidate aircraft source; no activation in this phase.",
    },
  },
  {
    id: "mobilitydata",
    name: "Mobility Database / MobilityData",
    priority: "B",
    domains: ["road", "rail"],
    coverage: "Global (feed dependent)",
    accessMethod: "DATASET_FILE_REVIEW_REQUIRED",
    updateFrequency: "WEEKLY",
    status: "prepared",
    license: {
      licenseStatus: "Review required per feed",
      commercialUse: "unknown",
      redistributionAllowed: "unknown",
      attributionRequired: true,
      notes: "Candidate feed registry; no production ingestion in this phase.",
    },
  },
  {
    id: "openmeteo",
    name: "Open-Meteo",
    priority: "B",
    domains: ["logistics"],
    coverage: "Global",
    accessMethod: "REST_API",
    updateFrequency: "REALTIME",
    status: "prepared",
    license: {
      licenseStatus: "Review required",
      commercialUse: "conditional",
      redistributionAllowed: "conditional",
      attributionRequired: true,
      notes: "Candidate weather connector for future operational context.",
    },
  },
];

export function getSourceDefinition(sourceId: string) {
  return sourceRegistry.find((source) => source.id === sourceId);
}
